// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvu4Vc4myNBni69AvmKEq7Y3bM4c5l0p4',
    appId: '1:382851062341:web:20e18ae4566877fb83a12c',
    messagingSenderId: '382851062341',
    projectId: 'jdlk-hackathon',
    authDomain: 'jdlk-hackathon.firebaseapp.com',
    databaseURL: 'https://jdlk-hackathon-default-rtdb.firebaseio.com',
    storageBucket: 'jdlk-hackathon.appspot.com',
    measurementId: 'G-2PWMW9GF50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClhINWcgNFRVwIZEGxIke9Fj724MUznJo',
    appId: '1:382851062341:android:7ce7530e5435f8b483a12c',
    messagingSenderId: '382851062341',
    projectId: 'jdlk-hackathon',
    databaseURL: 'https://jdlk-hackathon-default-rtdb.firebaseio.com',
    storageBucket: 'jdlk-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu7ztuoWPOc4f8WI_iKU-d6HNoJpuxcfk',
    appId: '1:382851062341:ios:9b4598d3b70ebf1183a12c',
    messagingSenderId: '382851062341',
    projectId: 'jdlk-hackathon',
    databaseURL: 'https://jdlk-hackathon-default-rtdb.firebaseio.com',
    storageBucket: 'jdlk-hackathon.appspot.com',
    androidClientId: '382851062341-925dr3eliatukl19ruob6s0a1g740ib2.apps.googleusercontent.com',
    iosClientId: '382851062341-m6rv3ev7c7hbf7jebc0vfcm8mugiijf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.receipts',
  );
}
